# Generated by Django 4.2.5 on 2024-11-23 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('designation', models.CharField(default='', max_length=100)),
                ('department', models.CharField(choices=[('fullfilment', 'Fullfilment'), ('logistics', 'Logistics'), ('dev', 'Developers'), ('sales', 'Sales & Marketing'), ('admin', 'HR & Admin'), ('accounting', 'Accounting')], default='fullfilment', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
