# Generated by Django 4.2.5 on 2026-08-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('email_enrollment', 'Email Enrollment')], default='login', max_length=20),
        ),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX auth_user_email_ci_unique "
                "ON auth_user (LOWER(email)) "
                "WHERE email <> '';"
            ),
            reverse_sql="DROP INDEX auth_user_email_ci_unique;",            
        )
    ]
