# Generated by Django 4.2.5 on 2026-08-22 12:43

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailotp_email_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(('consumed_at__isnull', True), ('invalidated_at__isnull', True), ('purpose', 'email_enrollment')), name='one_active_enrollment_otp_per_email_ci'),
        ),
    ]
