# Generated by Django 4.2.5 on 2023-10-22 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('expense_date', models.DateField()),
                ('category', models.CharField(choices=[('ads', 'Advertisement'), ('coms', 'Communication'), ('electricity', 'Electricity'), ('entertain', 'Entertainment'), ('food', 'Food'), ('insurance', 'Insurance'), ('internet', 'Internet'), ('loan', 'Loan'), ('maintenance', 'Maintenance'), ('misc', 'Miscellaneous'), ('prof_fee', 'Professional Fee'), ('rent', 'Rent'), ('salary', 'Salary'), ('software', 'Software'), ('tax', 'Taxes & Legal Fees'), ('tool', 'Tools & Equipments'), ('transpo', 'Transportation & Fuel'), ('water', 'Water'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
