# Generated by Django 4.2.5 on 2023-10-07 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('reason', models.CharField(choices=[('deliver', 'Deliver'), ('returned', 'Returned Item'), ('pull_out', 'Pull-out'), ('wrong_input', 'Wrong Input')], default='deliver', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventory.product')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
    ]
