# Generated by Django 4.2.5 on 2024-10-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_delivery_running_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
