# Generated by Django 4.2.5 on 2026-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_delivery_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
