# Generated by Django 4.2.5 on 2025-01-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payslips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslip',
            name='allowance',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_allowance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
